"""extra_break

Revision ID: 1fb70a4c2ff8
Revises: 2dd72f7178e0
Create Date: 2022-01-27 23:34:59.659626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fb70a4c2ff8'
down_revision = '2dd72f7178e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mock_interview_setup', sa.Column('extra_break', sa.String(), nullable=True))
    op.create_index(op.f('ix_mock_interview_setup_extra_break'), 'mock_interview_setup', ['extra_break'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mock_interview_setup_extra_break'), table_name='mock_interview_setup')
    op.drop_column('mock_interview_setup', 'extra_break')
    # ### end Alembic commands ###
