"""mock email and reference

Revision ID: 2dd72f7178e0
Revises: d4a9fb846936
Create Date: 2022-01-27 18:35:31.461977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dd72f7178e0'
down_revision = 'd4a9fb846936'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mock_interview_sign_up', sa.Column('reference', sa.String(), nullable=True))
    op.add_column('mock_interview_sign_up', sa.Column('email', sa.String(), nullable=True))
    op.create_index(op.f('ix_mock_interview_sign_up_email'), 'mock_interview_sign_up', ['email'], unique=False)
    op.create_index(op.f('ix_mock_interview_sign_up_reference'), 'mock_interview_sign_up', ['reference'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mock_interview_sign_up_reference'), table_name='mock_interview_sign_up')
    op.drop_index(op.f('ix_mock_interview_sign_up_email'), table_name='mock_interview_sign_up')
    op.drop_column('mock_interview_sign_up', 'email')
    op.drop_column('mock_interview_sign_up', 'reference')
    # ### end Alembic commands ###
