"""empty message

Revision ID: 7ab4d664092e
Revises: 6f4b8d5378ec
Create Date: 2021-11-30 18:22:40.868862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ab4d664092e'
down_revision = '6f4b8d5378ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Event', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_Event'), 'log', ['Event'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_log_Event'), table_name='log')
    op.drop_table('log')
    # ### end Alembic commands ###
