"""AvailableTimes

Revision ID: b041edd8278f
Revises: 9e57846cc284
Create Date: 2021-11-30 00:34:33.068199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b041edd8278f'
down_revision = '9e57846cc284'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('available_times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weekend', sa.Boolean(), nullable=False),
    sa.Column('appointment_hours', sa.String(), nullable=True),
    sa.Column('specific_dates', sa.String(), nullable=True),
    sa.Column('no_appointment', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('available_times')
    # ### end Alembic commands ###
