"""empty message

Revision ID: b0f0c5987897
Revises: 
Create Date: 2021-11-25 01:10:32.254438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0f0c5987897'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_user_name'), 'admin_user', ['name'], unique=False)
    op.create_table('appointments',
    sa.Column('ref_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.Column('email', sa.String(length=45), nullable=True),
    sa.Column('app_type', sa.String(length=45), nullable=True),
    sa.Column('date_time', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ref_id')
    )
    op.create_index(op.f('ix_appointments_app_type'), 'appointments', ['app_type'], unique=False)
    op.create_index(op.f('ix_appointments_date_time'), 'appointments', ['date_time'], unique=False)
    op.create_index(op.f('ix_appointments_email'), 'appointments', ['email'], unique=False)
    op.create_index(op.f('ix_appointments_name'), 'appointments', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointments_name'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_email'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_date_time'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_app_type'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_admin_user_name'), table_name='admin_user')
    op.drop_table('admin_user')
    # ### end Alembic commands ###
