"""MockInterviewSetupcomp

Revision ID: bc4e18c71ea3
Revises: c1d504ccf88f
Create Date: 2022-01-17 21:03:45.416123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc4e18c71ea3'
down_revision = 'c1d504ccf88f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mock_interview_setup', sa.Column('companies', sa.String(), nullable=True))
    op.create_index(op.f('ix_mock_interview_setup_companies'), 'mock_interview_setup', ['companies'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mock_interview_setup_companies'), table_name='mock_interview_setup')
    op.drop_column('mock_interview_setup', 'companies')
    # ### end Alembic commands ###
