"""MockInterviewSetup

Revision ID: c1d504ccf88f
Revises: c582141f54f4
Create Date: 2022-01-17 20:18:54.953109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1d504ccf88f'
down_revision = 'c582141f54f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mock_interview_setup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.String(), nullable=True),
    sa.Column('end_date', sa.String(), nullable=True),
    sa.Column('start_time', sa.String(), nullable=True),
    sa.Column('end_time', sa.String(), nullable=True),
    sa.Column('break_time', sa.String(), nullable=True),
    sa.Column('interval', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mock_interview_setup_break_time'), 'mock_interview_setup', ['break_time'], unique=False)
    op.create_index(op.f('ix_mock_interview_setup_end_date'), 'mock_interview_setup', ['end_date'], unique=False)
    op.create_index(op.f('ix_mock_interview_setup_end_time'), 'mock_interview_setup', ['end_time'], unique=False)
    op.create_index(op.f('ix_mock_interview_setup_interval'), 'mock_interview_setup', ['interval'], unique=False)
    op.create_index(op.f('ix_mock_interview_setup_start_date'), 'mock_interview_setup', ['start_date'], unique=False)
    op.create_index(op.f('ix_mock_interview_setup_start_time'), 'mock_interview_setup', ['start_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mock_interview_setup_start_time'), table_name='mock_interview_setup')
    op.drop_index(op.f('ix_mock_interview_setup_start_date'), table_name='mock_interview_setup')
    op.drop_index(op.f('ix_mock_interview_setup_interval'), table_name='mock_interview_setup')
    op.drop_index(op.f('ix_mock_interview_setup_end_time'), table_name='mock_interview_setup')
    op.drop_index(op.f('ix_mock_interview_setup_end_date'), table_name='mock_interview_setup')
    op.drop_index(op.f('ix_mock_interview_setup_break_time'), table_name='mock_interview_setup')
    op.drop_table('mock_interview_setup')
    # ### end Alembic commands ###
