"""Log_table_time

Revision ID: c582141f54f4
Revises: 621fe72841f8
Create Date: 2021-11-30 19:17:37.539595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c582141f54f4'
down_revision = '621fe72841f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log_storage', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_log_storage_timestamp'), 'log_storage', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_log_storage_timestamp'), table_name='log_storage')
    op.drop_column('log_storage', 'timestamp')
    # ### end Alembic commands ###
