"""log table

Revision ID: c6a2c8c9b1d4
Revises: b041edd8278f
Create Date: 2021-11-30 18:14:38.423597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6a2c8c9b1d4'
down_revision = 'b041edd8278f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Event', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'Event')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log')
    # ### end Alembic commands ###
