"""MockInterviewSignUp

Revision ID: d4a9fb846936
Revises: bc4e18c71ea3
Create Date: 2022-01-18 19:53:23.033955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4a9fb846936'
down_revision = 'bc4e18c71ea3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mock_interview_sign_up',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('major', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('time', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mock_interview_sign_up_company'), 'mock_interview_sign_up', ['company'], unique=False)
    op.create_index(op.f('ix_mock_interview_sign_up_date'), 'mock_interview_sign_up', ['date'], unique=False)
    op.create_index(op.f('ix_mock_interview_sign_up_major'), 'mock_interview_sign_up', ['major'], unique=False)
    op.create_index(op.f('ix_mock_interview_sign_up_name'), 'mock_interview_sign_up', ['name'], unique=False)
    op.create_index(op.f('ix_mock_interview_sign_up_time'), 'mock_interview_sign_up', ['time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mock_interview_sign_up_time'), table_name='mock_interview_sign_up')
    op.drop_index(op.f('ix_mock_interview_sign_up_name'), table_name='mock_interview_sign_up')
    op.drop_index(op.f('ix_mock_interview_sign_up_major'), table_name='mock_interview_sign_up')
    op.drop_index(op.f('ix_mock_interview_sign_up_date'), table_name='mock_interview_sign_up')
    op.drop_index(op.f('ix_mock_interview_sign_up_company'), table_name='mock_interview_sign_up')
    op.drop_table('mock_interview_sign_up')
    # ### end Alembic commands ###
